
# Este fichero sustituye a "application.properties", ya que es mas facil de mantener y configurar a traves del asistente.


##### Application properties: ####
# Todas la prpiedades que se pueden configurar de Spring en: 
#         http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html


# ServerProperties
server:
  port: 8089
  
 
# THYMELEAF (ThymeleafAutoConfiguration)
spring: 
  thymeleaf: 
    cache: true                      # Enable template caching
    encoding: UTF-8                  # Template encoding
    prefix: classpath:/templates/    # Prefix that gets prepended to view names when building a URL.
    suffix: .html                    # Suffix that gets appended to view names when building a URL.
  
  #Base de datos  
  datasource:
    url: jdbc:mysql://localhost:3306/0000_curso_spring_boot_MAMA
    username: root
    password: tente
  
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
      
    
    
  
# Banner
banner:
  location: classpath:banner.txt     # Fichero que contiene el texto del banner que se muestra al arrancar el servidor.
     


      





### Ejemplo del proyecto
 
#Spring properties 
#spring: 
#  aop:
#    auto: true
#    proxy-target-class: false
#  messages:
#    always-use-message-format: false  
#    basename: messages
#    cache-seconds: -1
#  mvc:
#    dispatch-trace-request: false
#    dispatch-options-request: true
#  couchbase:
#    bucket:
#      name: default
#

#Security properties      
#security: 
#  oauth2:
#    resource:
#      prefer-token-info: true
#      service-id: resource
    
    